### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'

### ISSUE THREAD

**Issue by rs1990** [jasperproject/jasper-client#426]
Hello,

Whenever i try to run jasper , I get the following error  :

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 77, in __init__
    self.config = yaml.safe_load(f)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
ParserError: while parsing a block mapping
  in "/home/pi/.jasper/profile.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/pi/.jasper/profile.yml", line 19, column 2
 ---------------------------------------------------------------------------------------------

when i run it as root i get : 

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 76, in __init__
    with open(new_configfile, "r") as f:
IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'
 

------------------------------------------------------------------------------------------------ 

I als ochecked and have the profile.yml file in  location : /home/pi/.jasper 

profile.yml =

carrier: tmomail.net
first_name: ###########
gmail_address: ########@######.com
gmail_password: ##########
last_name: #######
location: ######
phone_number: '##########'
prefers_email: true
stt_engine: sphinx
pocketsphinx:
  fst_model: '/home/pi/jasper/is2013-conversion/models/g014b2b.fst'                    
  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' 
timezone: ##########
tts_engine: espeak-tts
espeak-tts:
  voice: 'default+m3'   # optional
  pitch_adjustment: 40  # optional
  words_per_minute: 160 # optional
 prefers_email: false
 timezone: ######
 keys:
FB_TOKEN:#######################

Any help please ......

thank you

**Comment by confessin** [comment]
Mind my ignorance but can you remove any blank lines if present in profile.yaml

**Comment by rs1990** [comment]
Hello,
I did. But still the same result. 

Thanks for the support.

**Comment by k0ssi** [comment]
running jasper as root is the wrong way cause jasper will search a profile.yml within the root user profile. 

please post your profile.yml within a code tag (see here: https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting).

**Comment by rs1990** [comment]
Hello ,

Sorry about that. wasnt aware of the syntax . here it is

'''
carrier: tmomail.net
first_name: ###########
gmail_address: ########@######.com
gmail_password: ##########
last_name: #######
location: ######
phone_number: '##########'
prefers_email: true
stt_engine: sphinx
pocketsphinx:
fst_model: '/home/pi/jasper/is2013-conversion/models/g014b2b.fst'
hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' 
timezone: ##########
tts_engine: espeak-tts
espeak-tts:
voice: 'default+m3' # optional
pitch_adjustment: 40 # optional
words_per_minute: 160 # optional
prefers_email: false
timezone: ######
keys:
FB_TOKEN:#######################
'''

**Comment by rs1990** [comment]
Hello,

i tried it as root and without. but no difference. 

I apologise ,
 i tried to put it within a code tag but it didnt change. im new and not got much experience.

**Comment by k0ssi** [comment]
please checkout my link within my last comment how to post code on github otherwise we are not able to detect syntax error coming from wrong placed spaces or something else.

**Comment by rs1990** [comment]
hello ,
Sorry about that. Here it is:

```
carrier: tmomail.net
first_name: #######
gmail_address: ##########
gmail_password: #############
last_name: ##########
location: ###########
phone_number: '#########'
prefers_email: true
stt_engine: sphinx
pocketsphinx:
  fst_model: '/home/pi/jasper/is2013-conversion/models/g014b2b.fst'                    
  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' 
timezone: ##########
tts_engine: espeak-tts
espeak-tts:
  voice: 'default+m3'   # optional
  pitch_adjustment: 40  # optional
  words_per_minute: 160 # optional
 prefers_email: false
 timezone: #######
 keys:
FB_TOKEN:#############
```
