### ISSUE TITLE
External plugins

### ISSUE THREAD

**Issue by iamtheib** [jasperproject/jasper-client#468]
I believe the new plugin system is a big step in the right direction. However, I have some proposals I would like to be discussed before I start implementing them.

From my understanding of the code (**[`Line 114: jasper/application.py`](https://github.com/jasperproject/jasper-client/blob/6f1d6c5c92017d6d779e45a88f8b0e81b6b36e4f/jasper/application.py#L114)`**), Jasper plugins can only be put in two places, for them to be recognized: `${CONFIG}/plugins` directory, and the plugins directory in the src.

##### Proposal 1: A way to tell Jasper where to find plugins

This can be done through the profile `YAML` file;
````yaml
plugins:
    - /absolute/path/to/a/plugin/directory
    - relative/path/to/another/plugin/directory # need to decide where this is relative to
    - plugin_name # this can be resolved to the default plugin location (e.g ${CONFIG}/plugins)
```` 
or something similar with the new config system.

The plugins paths defined in the config will be resolved, along with the plugins in the src, to form the complete list of plugins.

##### Proposal 2: Make plugins 'opt-in'

Some people have their own versions of the plugins packaged with Jasper. Trying to get Jasper to recognize these modified versions, that listen to the same keywords as the packaged plugins, involves playing around with the priority level of one of the plugins.

###### Option 1

Take all the plugins out of the main src, and have them installed separately. Then the user can choose what plugins to use with Jasper. This also decouples Jasper from the plugins.

###### Option 2

Leave the plugins as part of the main src, and have a way for users to exclude certain plugins.

These can be done through the profile `YAML` file;
````yaml
plugins:
    include:
        - /absolute/path/to/a/plugin/directory
        - relative/path/to/another/plugin/directory # need to decide where this is relative to
        - weather # if all plugins are taken out of the main src
    exclude:
        - birthday # if plugins are left in the main src but can opt out
        - /absolute/path/to/a/plugin/directory/sub_plugin
```` 
or something similar with the new config system.

I believe regardless of the preferred option, having a way to exclude plugins from being used, would be nice.

Please let me know what you think.
