### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by sanjayshreedharan** [jasperproject/jasper-client#545]
Hello,

I installed jasper on Raspberry Pi3 and successfully got the english version of it working. I used pocketsphinx for STT and google-tts for TTS. Now, I want jasper to work with other languages like French / German. I downloaded the acoustic model for French and changed the hmm_dir location in line 73 of stt.py to refer to the French model. Also, I changed the line WORDS = ["TIME"] to WORDS = ["TEMPS"] in the file time.py in modules. Now, I run jasper and when I try to speak to it, nothing happens. Whatever I speak it doesn't convert it to text. The transcribed text is always " ". Can you please help me solve this problem so that jasper works with french? Do I have to make changes to any other files?

**Comment by andreaskoelsch** [comment]
I had the same problem. My workaround was the following: 
- Change language in profile to target language, but leave the models for english language.
- Copy english dictionary to target language
- Have Jasper waiting for the keyword with the english model and dictionary.
- Use google voice api for active listening with target language.

**Comment by sanjayshreedharan** [comment]
Hello,

I was unable to get what you were trying to convey. Can you please be a bit more elaborate on it?

**Comment by andreaskoelsch** [comment]
You can use pocketsphinx for passive listening and google voice for active listening. This is how I got german working.

This is what ~/.jasper/profile.yml looks like

```
stt_engine: google
stt_passive_engine: sphinx
language: de-DE
pocketsphinx:
  fst_model: '/home/pi/phonetisaurus/g014b2b.fst'
  hmm_dir: '/usr/local/share/pocketsphinx/model/en-us/hub4wsj_sc_8k'
keys:
    GOOGLE_SPEECH: your_api_key
```

Now you should cp the standard phrases of en-US to de-DE or french.

Then you can say "Jasper" (in english), it will beep and then you talk french/german/whatever - the active listening will be handled by google.


PS: Are you working with jasper-dev? I do. Could be different for master. You have to try.
