### ISSUE TITLE
Problem with Julius 

### ISSUE THREAD

**Issue by zack2213** [jasperproject/jasper-client#688]
Hello All....can you be more specific about file and path....sory im too newbie in linux...im already set path as it ask...but its still showing ...

   f = tf.extractfile(membername)
  File "/usr/lib/python2.7/tarfile.py", line 2145, in extractfile
    tarinfo = self.getmember(member)
  File "/usr/lib/python2.7/tarfile.py", line 1829, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename '/home/pi/julius/VoxForge/VoxForgeDict' not found"
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 146, in <module>
    app = Jasper()
  File "jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
KeyError: "filename '/home/pi/julius/VoxForge/VoxForgeDict' not found"

please im need help....need to finish in few more days

**Comment by G10DRAS** [comment]
Try config like this

```
julius:
  hmmdefs:  /home/pi/julius/hmmdefsAdapt
  tiedlist: /home/pi/julius/tiedlistAdapt
  lexicon:  /home/pi/julius/VoxForge.tgz
  lexicon_archive_member: VoxForge/VoxForgeDict
```

see last parameter

`lexicon_archive_member: VoxForge/VoxForgeDict`
