### ISSUE TITLE
ImportError: No module named req

### ISSUE THREAD

**Issue by asyraafqayyum** [jasperproject/jasper-client#699]
After entering this >> pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
I got this errors:
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 13, in <module>
    from client import stt
  File "/home/pi/jasper/client/stt.py", line 16, in <module>
    import diagnose
  File "/home/pi/jasper/client/diagnose.py", line 9, in <module>
    import pip.req
ImportError: No module named req

By reading solutions to similar error, i have enter this code to change the pip version:
sudo python -m pip install --upgrade pip==9.0.3

Then this error come:

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/pi/phonetisaurus/g014b2b.fst --input=/tmp/tmpakf5pP.g2p --words --isfile' return with exit status -11
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 321, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/pi/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/pi/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/pi/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed
 Can anyone help me? im really bad at this :(

**Comment by G10DRAS** [comment]
see this error 

`ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/pi/phonetisaurus/g014b2b.fst --input=/tmp/tmpakf5pP.g2p --words --isfile' return with exit status -11`

did you installed `phonetisaurus-g2p` and `/home/pi/phonetisaurus/g014b2b.fst`

**Comment by asyraafqayyum** [comment]
Im following to install phonetisaurus :
http://jasperproject.github.io/documentation/configuration/

Build Phonetisaurus:
```
cd is2013-conversion/phonetisaurus/src
sudo make
```

Move some of the compiled files:
```
sudo cp ~/m2m-aligner-1.2/m2m-aligner /usr/local/bin/m2m-aligner
sudo cp ~/is2013-conversion/bin/phonetisaurus-g2p /usr/local/bin/phonetisaurus-g2p
```

Building the Phonetisaurus FST model:
```
wget https://www.dropbox.com/s/kfht75czdwucni1/g014b2b.tgz
tar -xvf g014b2b.tgz
```

Build Phonetisaurus model:
```
cd g014b2b/
./compile-fst.sh
cd ..
```

Is the command above correct? May i ask the command to install them? Thanks a lot :D

my profile:
```
carrier: ''
first_name: Asyraaf
gmail_address: ''
gmail_password: ''
last_name: ''
phone_number: '123456789'
prefers_email: true
stt_engine: sphinx
pocketsphinx:
  fst_model: '/home/pi/phonetisaurus/g014b2b.fst'                             
  hmm_dir: '/usr/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' 
timezone: Asia/Kuala_Lumpur
tts_engine: mary-tts
mary-tts:
  server: 'tts.mattcurry.com'
  port: '59125'
  language: 'en_US'
  voice: 'cmu-slt-hsmm'
```
