### ISSUE TITLE
Running Jasper for the first time - could not find expected ':'

### ISSUE THREAD

**Issue by JPychon** [jasperproject/jasper-client#723]
Hello! I've just recently installed Jasper and I am trying to run it for the first time. However, I keep getting this error

```
ScannerError: while scanning a simple key
  in "/home/pi/.jasper/profile.yml", line 14, column 1
could not find expected ':'
  in "/home/pi/.jasper/profile.yml", line 14, column 4

```

This is my .yaml file:
```
carrier: carriername
first_name: firstname
gmail_address: email
gmail_password: password
last_name: lastname
phone_number: '000-000-0000'
prefers_email: false
stt_engine: sphinx
timezone: America/Los_Angeles
pocketsphinx:
    hmm_dir: '/usr/share/pocketsphinx/model/en-us/en-us'
    fst_model: '../phonetisaurus/g014b2b.fst'
tts_engine: festival-tts
EOF
```
I am kinda new to this but I am not really sure where am I missing the colon?
